### ISSUE TITLE
RuntimeError: input must have 3 dimensions, got 2

### ISSUE THREAD

**Issue by clemsciences** [mpsilfve/phonembedding#2]
I have an other error in rnn.py:

```python
1. CORRELATION EXPERIMENTS
--------------------------

Traceback (most recent call last):
  File "C:/Users/Clément/PycharmProjects/phonembedding/src/main.py", line 102, in <module>
    train(data,modeld)
  File "C:\Users\Clément\PycharmProjects\phonembedding\src\rnn.py", line 124, in train
    totloss += update(lemma,tags,wf,modeldict)
  File "C:\Users\Clément\PycharmProjects\phonembedding\src\rnn.py", line 110, in update
    cdistrs, chars = decode(encoded,modeldict,len(wf))
  File "C:\Users\Clément\PycharmProjects\phonembedding\src\rnn.py", line 98, in decode
    _, states = modeldict['dec'](input,(h,c))
  File "C:\Users\Clément\PycharmProjects\phonembedding_clemsciences\venv\lib\site-packages\torch\nn\modules\module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\Clément\PycharmProjects\phonembedding_clemsciences\venv\lib\site-packages\torch\nn\modules\rnn.py", line 178, in forward
    self.check_forward_args(input, hx, batch_sizes)
  File "C:\Users\Clément\PycharmProjects\phonembedding_clemsciences\venv\lib\site-packages\torch\nn\modules\rnn.py", line 126, in check_forward_args
    expected_input_dim, input.dim()))
RuntimeError: input must have 3 dimensions, got 2
```
when I run main.py:

```python
    data, cencoder, tencoder, embchars = readdata('../data/finnish',"FI")
    modeld = initmodel(cencoder,tencoder,15)
    encoded = encode(data[0][1],data[0][2],modeld)
    train(data,modeld)
```

**Comment by mpsilfve** [comment]
Hi, This should be fixed now. Though the new code uses dynet not pytorch.
